CREATE TABLE public."Account" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Username" varchar(100) NULL,
	"Password" varchar(200) NULL,
	"Email" varchar(100) NULL,
	"Confirmed" bool NOT NULL,
	CONSTRAINT "PK_Account" PRIMARY KEY ("Id")
);

CREATE TABLE public."User" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Title" varchar(20) NULL,
	"Subtitle" varchar(50) NULL,
	"Description" varchar(300) NULL,
	"Nickname" varchar(40) DEFAULT ''::character varying NOT NULL,
	"AccountId" int8 NULL,
	"Gif" text NULL,
	"Photo" text NULL,
	"Pronouns" text NULL,
	"Song" text NULL,
	CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_User_AccountId" ON public."User" USING btree ("AccountId");
ALTER TABLE public."User" ADD CONSTRAINT "FK_User_Account_AccountId" FOREIGN KEY ("AccountId") REFERENCES public."Account"("Id");

CREATE TABLE public."Interests" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" int8 NOT NULL,
	"Interest" varchar(30) NOT NULL,
	"Emoji" varchar(5) NULL,
	CONSTRAINT "PK_Interests" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Interests_UserId" ON public."Interests" USING btree ("UserId");
ALTER TABLE public."Interests" ADD CONSTRAINT "FK_Interests_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;

CREATE TABLE public."Layout" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" int8 NOT NULL,
	"BorderRadius" varchar(10) NULL,
	"CardBackgroundColor" varchar(10) NULL,
	"PageBackgroundColor" varchar(10) NULL,
	"FontFamily" varchar(20) NULL,
	"FontColor" varchar(10) NULL,
	"BaseLayout" varchar(40) NULL,
	"TitleColor" varchar(10) NULL,
	CONSTRAINT "PK_Layout" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Layout_UserId" ON public."Layout" USING btree ("UserId");
ALTER TABLE public."Layout" ADD CONSTRAINT "FK_Layout_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;

CREATE TABLE public."ProfileLinks" (
	"Id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" int8 NOT NULL,
	"Type" varchar(40) DEFAULT ''::character varying NOT NULL,
	"Value" varchar(100) DEFAULT ''::character varying NOT NULL,
	"Action" varchar(20) DEFAULT ''::character varying NOT NULL,
	CONSTRAINT "PK_ProfileLinks" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_ProfileLinks_UserId" ON public."ProfileLinks" USING btree ("UserId");
ALTER TABLE public."ProfileLinks" ADD CONSTRAINT "FK_ProfileLinks_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;